spring.profiles.active=springai-multi
spring.profiles.default=plain
spring.application.name=conference-agent
openai.proxy.url=https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
openai.proxy.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXR0cm8iLCJncnAiOiJ3b3Jrc2hvcCIsImlhdCI6MTc1NTc5MjkwMCwiZXhwIjoxNzU1ODAzNzAwfQ.a7fghG2VeVJPwmwvPsCmA2fQhsgTspIkh4ZBEKXW3_k

spring.ai.openai.project-id=workshop
embabel.agent.platform.models.openai.base-url=${openai.proxy.url}/v1
spring.ai.openai.api-key=${openai.proxy.token}
spring.ai.openai.model=gpt-4.1-mini
spring.ai.openai.chat-model=gpt-4.1-mini
spring.ai.openai.embedding-model=text-embedding-3-small

embabel.models.default-llm=gpt-4.1-mini
embabel,agent-platform.ranking.llm=gpt-4.1-mini

logging.level.root=INFO
