spring.profiles.active=
spring.profiles.default=plain
spring.application.name=conference-agent
openai.proxy.url=https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
openai.proxy.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqZXR0cm8iLCJncnAiOiJ3b3Jrc2hvcCIsImlhdCI6MTc1NTEwMjA1OCwiZXhwIjoxNzU1MTEyODU4fQ.VJS_uCfIZvonul0sT0FUN5i2NvtdyVaQ4h7hIeAatqs
