spring.profiles.active=
spring.profiles.default=plain
spring.application.name=conference-agent
openai.proxy.url=https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
openai.proxy.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrZWVzIiwiZ3JwIjoid29ya3Nob3AiLCJpYXQiOjE3NTUxNzgyOTQsImV4cCI6MTc1NTE4OTA5NH0._ANLHkDoZoFSLJ_4XUdfip-CJBzTxjbt8a6HJ54-xdg
