spring:
  profiles:
    active: springai
    default: plain
  application:
    name: conference-agent
  ai:
    chat:
      observations:
        log-prompt: true
        log-completion: true
        include-content: true

    openai:
      project-id: workshop
      api-key: ${openai.proxy.token}
      model: gpt-4.1-mini
      chat-model: gpt-4.1-mini
      embedding-model: text-embedding-3-small
    ollama:
      base-url: http://localhost:11434
    mcp:
      client:
        enabled: true
        type: SYNC
        stdio:
          connections:
            time:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/time
                - --local-timezone=America/New_York

openai:
  proxy:
    url: https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3R1ZGVudCIsImRlc2NyaXB0aW9uIjoid29ya3Nob3AiLCJpYXQiOjE3NTcyNzAwOTUsImV4cCI6MTc1NzI4MDg5NX0.E3ClcWR1lso-uXyZqsh5Sa-Xd8Mm7vj41SsjI7mw7p0
embabel:
  agent:
    platform:
      models:
        openai:
          base-url: ${openai.proxy.url}/v1
  models:
    default-llm: gpt-4.1-mini
  agent-platform:
    ranking:
      llm: gpt-4.1-mini
logging:
  level:
    root: INFO
